### PR TITLE
Removing FITS: Slim down

### LINKED ISSUE #34: Remove FITS files
Hi @Hoeijmakers,

Quick notes: 

1. It's best practice to keep the file sizes in the github repo small. Here are the [astropy data file guidelines](https://docs.astropy.org/en/stable/development/codeguide.html#data-and-configuration) which recommend keeping all file data to <100 kB. You're normally supposed to accomplish this by hosting the data files somewhere else (like a personal webpage) and then [downloading them](https://docs.astropy.org/en/stable/api/astropy.utils.data.download_file.html) when needed from your script. 

2. One of the reasons this is preferred is that git will go line-by-line through the data files (binaries, yikes!) to look for diffs, and that makes git very slow. For example it took me a _full minute_ just to pull the latest changes which added the FITS files.

3. You can follow a recipe [like this](https://docs.astropy.org/en/stable/development/workflow/development_workflow.html#how-to-squash) (preferred) or [like this](https://dev.to/morinoko/useful-git-commands-for-removing-accidentally-pushed-or-committed-files-2ld) to remove the data files from the history completely (so they don't slow/weigh down new clones every time you run them). Just make sure you have a copy of those files somewhere on your machine before you tinker with your repo's history.

### PR DESCRIPTION
**Pull request by bmorris3**
This reworking of the file history of `tayph` should be examined carefully (and you should backup tayph elsewhere) before you merge this pull request. 

I've deleted the large FITS files as recommended #34, then squashed the commit history so that the history skips right over the additions and later deletions of those files, so they no longer appear in the git history at all. All other changes to the files in the package should be addressed in this PR. Please make sure this is true, just in case. The number of commits here and in your old history won't match up due to the squashing process, but the file changes should all be preserved except those having to do with PHOENIX files.

I also added a new submodule called `phoenix` that queries for the exact same FITS files that you had downloaded and stored in this package. The API makes it easy to download the PHOENIX FITS files and cache them in your astropy cache indefinitely. I haven't yet replaced the few calls in the `tayph` package to the PHOENIX files with calls to the new querying functions yet, happy to implement that if the rest of this PR looks good.

Fixes #34

### CODE REVIEW

**Comment by bmorris3** [comment]
Also: you may want to merge this one (if it looks good) before #35.

**Comment by bmorris3** [comment]
> I haven't yet replaced the few calls in the tayph package to the PHOENIX files with calls to the new querying functions yet, happy to implement that if the rest of this PR looks good.

I've implemented this change in 2154f3c.

**Comment by Hoeijmakers** [comment]
Thanks Brett! I have merged this request after backing up Tayph, and nothing seems to be broken. I also offloaded the sky telluric model to a google drive, so that's all good. However, the FITS files that you deleted still show up in my git history. They are still part of the master branch currently. I deleted them locally and git registers that as a file change. I'm not sure why they have persisted, but it may have to do with the fact that I have kept committing and pushing changes (only to py files though) while your PR was open? How should I go about eliminating these big files?

**Comment by Hoeijmakers** [comment]
Sorry, I just saw the issue that you opened and I will comment there further.

**Comment by bmorris3** [comment]
That could be because you needed to rebase the PR I submitted instead – that's one of the options you get when you click the dropdown menu next to the big green merge button. You could try using BFG or `git filter-branch` to remove those files and push the changes.

**Pull request merged**
